name: Main Action
on: workflow_dispatch

jobs:
  job1:
    uses: awesome-linus/github-actions_workflow_call/.github/workflows/reusable_workflow.yml@main
    with:
      name: Kou
  job2:
    name: Output Job
    runs-on: ubuntu-latest
    needs: 
      - job1
    steps:
      - name: Output Hello World
        run: echo ${{ needs.job1.outputs.hello_world }}
